### ISSUE TITLE
Microsoft Word crashing when trying to use Mahou

### ISSUE THREAD

**Issue by MiLate** [BladeMight/Mahou#98] opened 2017-06-23 09:45 UTC
## Problem/Request description

Microsoft Word crashing when trying to use Mahou.

**Comment by BladeMight** [comment] 2017-06-23 09:49
@MiLate Which version of Word, and please paste here debug info from Mahou about tab. ([ENG](https://github.com/BladeMight/Mahou/wiki/Functions-list#debug-info)/[RUS](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F))

**Comment by ailintom** [comment] 2017-09-11 13:07
I also have Word 2016 (Version 1707 (Build 8326.2096) crashing when using Mahou. I switch from Word to another program, change the keyboard layout a couple of times with Mahou, get back to word, and it freezes.

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>


- Mahou 2.5.0.1
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

German(67568647)
Ägyptologische Umschrift - Deutsch(4039246855)
US(67699721)
Translittération de l égyptien(4039181324)
Russian(68748313)
Egyptian Transliteration(4039115830)
Arabic (101)(67177473)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=true
[Functions]
AutoStartAsAdmin=false
TrayIconVisible=True
ConvertSelectionLayoutSwitching=False
ReSelect=True
RePress=False
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=False
CapsLockTimer=True
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
GuessKeyCodeFix=False
AppDataConfigs=False
[Layouts]
SwitchBetweenLayouts=True
OneLayout=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=US(67699721)
MainLayout2=Russian(68748313)
SpecificKey1=3
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Switch between layouts
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
QWERTZfix=False
[PersistentLayout]
ActivateForLayout1=False
ActivateForLayout2=False
Layout1CheckInterval=50
Layout2CheckInterval=50
Layout1Processes=devenv.exe wdexpress.exe
Layout2Processes=notepad++.exe winword.exe
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
MouseLTAlways=False
Language=English
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif, 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif, 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif, 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif, 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
MouseLTUseFlags=False
CaretLTUseFlags=False
Layout1LTText=
Layout2LTText=
MouseLTUpperArrow=False
CaretLTUpperArrow=False
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
SwitchToGuessLayout=False
[AutoSwitch]
Enabled=False
SpaceAfter=True
SwitchToGuessLayout=True
DownloadInZip=True
[Hotkeys]
ToggleMainWindow_Enabled=True
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=True
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=True
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=True
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=0
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Alt
SelectedTextToRandomCase_Key=0
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win
SelectedTextToSwapCase_Key=190
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=True
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=True
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=True
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
[LangPanel]
Display=False
Transparency=90
RefreshRate=25
Position=X0 Y0
ForeColor=#000000
BackColor=#FFFFFF
Font=Microsoft Sans Serif, 25pt
BorderColor=#8B5FFF
BorderAeroColor=True
UpperArrow=True
[Updates]
Channel=Stable
LatestCommit=
```
</details>
</details>
</details>

**Comment by BladeMight** [comment] 2017-09-11 13:09
@ailintom OK, will test Mahou with Word 2016 later.

**Comment by BladeMight** [comment] 2017-09-11 21:28
@ailintom I could not reproduce it in Word 2016(v16.0.4266.1001), here image with things i do(as you said i switched to Word, converted something, switched to another program(Notepad), changed layout(also tried a dozen of times, result same) returned to Word, and no Freeze):
![mahou works with word-2016](https://user-images.githubusercontent.com/11931888/30297392-4f66ff2e-9750-11e7-9363-58b00c7e8787.gif)

P.S. Mahou used in screenshot is latest-commit version, you can update from updates tab to it and try with it, (though i tried older versions, they got same result.)

...

Still need more info,,,,

**Comment by ailintom** [comment] 2017-09-12 09:01
I may be wrong but it seems the problem occurs when there are additional language packs/proofing tools installed in Word AND Mahou is used (in my case the problem seems to disappear either when I close Mahou and switch layouts manually OR in a fresh installation of Office without the language packs with Mahou running).  (I'd wonder whether @MiLate had any language packs installed).

**Comment by BladeMight** [comment] 2017-09-12 16:00
@ailintom OK, will install language packs and test it, i'll write results later.

**Comment by BladeMight** [comment] 2017-09-15 11:41
@ailintom Test the `latest-commit` version, seems i make it better now.

**Comment by ailintom** [comment] 2017-09-15 15:03
@BladeMight Thanks a lot!   
At first sight, the problem seems to be gone. But I'll keep on testing.

**Comment by BladeMight** [comment] 2017-09-15 16:13
@ailintom Just now i did one another commit in which i added support for `switch between layouts` and `emulate layout switching` to work together, which will fix the crashing of apps like MSOffice2016. How to enable:
Enable `switch between layouts` and `emulate layout switching` in layouts tab.

**Comment by BladeMight** [comment] 2017-09-15 16:51
@ailintom Added info about fix for MSOffice2016 and simillar to [wiki](https://github.com/BladeMight/Mahou/wiki/Problems-in-some-programs%3F#microsoft-office-2016skype-and-similar), release [Mahou-v2.5.1.0](https://github.com/BladeMight/Mahou/releases/tag/v2.5.1.0).
With the fix i wrote at wiki MSOffice won't crash ever, so i close the issue.

**Closed by BladeMight** 2017-09-15 16:51 UTC
Labels: Need More Info, Probably fixed

**Comment by ailintom** [comment] 2017-09-15 16:57
I understand that emulate layout switching switches between all installed
layouts. (I only need to switch between the two while I have totally 6
installed)

Am 15.09.2017 6:13 nachm. schrieb "BladeMight" <notifications@github.com>:

**Comment by BladeMight** [comment] 2017-09-15 16:59
@ailintom Please read the [wiki](https://github.com/BladeMight/Mahou/wiki/Problems-in-some-programs%3F#microsoft-office-2016skype-and-similar), the thing i added is to switch between those two using emulate layout switching.
